Repository element-hq/matrix-authentication-service, pull requests merged in 2024-12, with the labels that each got.

#3307 New job queue: worker registration and leader election
  Cargo.lock
  Cargo.toml
  crates/cli/src/commands/server.rs
  crates/cli/src/commands/worker.rs
  crates/storage-pg/.sqlx/query-12c4577701416a9dc23708c46700f3f086e4e62c6de9d6864a6a11a2470ebe62.json
  crates/storage-pg/.sqlx/query-399e261027fe6c9167511636157ab747a469404533f59ff6fbd56e9eb5ad38e1.json
  crates/storage-pg/.sqlx/query-5f2199865fae3a969bb37429dd70dc74505b22c681322bd99b62c2a540c6cd35.json
  crates/storage-pg/.sqlx/query-67cd4880d84b38f20c3960789934d55cbfb01492985ac2af5a1ad4af9b3ccc77.json
  crates/storage-pg/.sqlx/query-6bd38759f569fcf972924d12f565b531b9873f4139eadcbf1450e726b9a27379.json
  crates/storage-pg/.sqlx/query-6ecad60e565367a6cfa539b4c32dabe674ea853e0d47eb5c713705cb0130c758.json
  crates/storage-pg/.sqlx/query-966ca0f7eebd2896c007b2fd6e9327d03b29fe413d57cce21c67b6d539f59e7d.json
  crates/storage-pg/.sqlx/query-fe7bd146523e4bb321cb234d6bf9f3005b55c654897a8e46dc933c7fd2263c7c.json
  crates/storage-pg/migrations/20241004075132_queue_worker.sql
  crates/storage-pg/src/lib.rs
  crates/storage-pg/src/queue/mod.rs
  crates/storage-pg/src/queue/worker.rs
  crates/storage-pg/src/repository.rs
  crates/storage/src/lib.rs
  crates/storage/src/queue/mod.rs
  crates/storage/src/queue/worker.rs
  crates/storage/src/repository.rs
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
  crates/tasks/src/new_queue.rs
  deny.toml
Labels: A-Jobs

#3367 Insert jobs using the new queue
  Cargo.lock
  crates/cli/src/commands/manage.rs
  crates/cli/src/commands/server.rs
  crates/cli/src/commands/worker.rs
  crates/handlers/src/admin/v1/users/add.rs
  crates/handlers/src/admin/v1/users/deactivate.rs
  crates/handlers/src/compat/logout.rs
  crates/handlers/src/graphql/mutations/compat_session.rs
  crates/handlers/src/graphql/mutations/oauth2_session.rs
  crates/handlers/src/graphql/mutations/user.rs
  crates/handlers/src/graphql/mutations/user_email.rs
  crates/handlers/src/oauth2/revoke.rs
  crates/handlers/src/upstream_oauth2/link.rs
  crates/handlers/src/views/account/emails/add.rs
  crates/handlers/src/views/account/emails/verify.rs
  crates/handlers/src/views/recovery/progress.rs
  crates/handlers/src/views/recovery/start.rs
  crates/handlers/src/views/register.rs
  crates/storage-pg/.sqlx/query-359a00f6667b5b1fef616b0c18e11eb91698aa1f2d5d146cffbb7aea8d77467b.json
  crates/storage-pg/.sqlx/query-e291be0434ab9c346dee777e50f8e601f12c8003fe93a5ecb110d02642d14c3c.json
  crates/storage-pg/migrations/20241004121132_queue_job.sql
  crates/storage-pg/src/job.rs
  crates/storage-pg/src/lib.rs
  crates/storage-pg/src/queue/job.rs
  crates/storage-pg/src/queue/mod.rs
  crates/storage-pg/src/repository.rs
  crates/storage/Cargo.toml
  crates/storage/src/job.rs
  crates/storage/src/lib.rs
  crates/storage/src/queue/job.rs
  crates/storage/src/queue/mod.rs
  crates/storage/src/queue/tasks.rs
  crates/storage/src/repository.rs
  crates/tasks/Cargo.toml
  crates/tasks/src/email.rs
  crates/tasks/src/lib.rs
  crates/tasks/src/matrix.rs
  crates/tasks/src/recovery.rs
  crates/tasks/src/user.rs
  deny.toml
Labels: A-Jobs

#3455 Consume jobs from the new job queue
  crates/storage-pg/.sqlx/query-07cd2da428f0984513b4ce58e526c35c9c236ea8beb6696e5740fa45655e59f3.json
  crates/storage-pg/.sqlx/query-47e74a8fc614653ffaa60930fafa8e4d1682263079ec09c38a20c059580adb38.json
  crates/storage-pg/.sqlx/query-707d78340069627aba9f18bbe5ac1388d6723f82549d88d704d9c939b9d35c49.json
  crates/storage-pg/.sqlx/query-a63a217981b97448ddcc96b2489ddd9d3bc8c99b5b8b1d373939fc3ae9715c27.json
  crates/storage-pg/.sqlx/query-f50b7fb5a2c09e7b7e89e2addb0ca42c790c101a3fc9442862b5885d5116325a.json
  crates/storage-pg/migrations/20241120163320_queue_job_failures.sql
  crates/storage-pg/src/queue/job.rs
  crates/storage/src/queue/job.rs
  crates/tasks/src/email.rs
  crates/tasks/src/lib.rs
  crates/tasks/src/matrix.rs
  crates/tasks/src/new_queue.rs
  crates/tasks/src/recovery.rs
  crates/tasks/src/storage/from_row.rs
  crates/tasks/src/storage/mod.rs
  crates/tasks/src/storage/postgres.rs
  crates/tasks/src/user.rs
  crates/tasks/src/utils.rs
Labels: A-Jobs

#3558 Allow scheduling jobs in the future
  crates/storage-pg/.sqlx/query-3355b3b5729d8240297a5ac8111ce891e626a82dcb78ff85f2b815d9329ff936.json
  crates/storage-pg/.sqlx/query-3c7960a2eb2edd71bc71177fc0fb2e83858c9944893b8f3a0f0131e8a9b7a494.json
  crates/storage-pg/.sqlx/query-47e74a8fc614653ffaa60930fafa8e4d1682263079ec09c38a20c059580adb38.json
  crates/storage-pg/.sqlx/query-d6c4cc9b04086f1b6ffad30d8a859e9fc0bf8a1fe9002dc3854ae28e65fc7943.json
  crates/storage-pg/migrations/20241122130349_queue_job_scheduled.sql
  crates/storage-pg/migrations/20241122133435_queue_job_scheduled_index.sql
  crates/storage-pg/src/queue/job.rs
  crates/storage/src/queue/job.rs
  crates/tasks/src/new_queue.rs
Labels: A-Jobs

#3654 Upgrade idna for RUSTSEC-2024-0421
  Cargo.lock
  Cargo.toml
  crates/handlers/Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend

#3679 Fix the Localazy download workflow
  .github/workflows/translations-download.yaml
Labels: A-CI, T-Task

#3678 Add metrics to the job queue
  Cargo.lock
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
  crates/tasks/src/new_queue.rs
Labels: A-Jobs

#3725 Include example SSO config for Rauthy.
  docs/setup/sso.md
Labels: A-Documentation
