Repository element-hq/matrix-authentication-service, pull requests merged in 2025-08, with the labels that each got.

#4856 Make `mas-cli manage issue-compatibility-token` create the device on the homeserver
  crates/cli/src/commands/manage.rs
Labels: A-CLI, A-Homeserver-Integration, T-Defect

#4890 Include simple script to generate an access token
  docs/SUMMARY.md
  docs/topics/access-token.md
  misc/device-code-grant.sh
Labels: A-Documentation

#4872 Enable the `urlencode` filter in `minijinja` templates
  Cargo.lock
  Cargo.toml
Labels: A-Templates, A-Upstream-OAuth, T-Task
