Repository element-hq/matrix-authentication-service, pull requests merged in 2025-04, with the labels that each got.

#4354 Bump all Rust dependencies
  Cargo.lock
  Cargo.toml
  crates/cli/src/telemetry.rs
  crates/handlers/Cargo.toml
  crates/policy/Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend

#4369 Allow requests to the compat login endpoint without a Content-Type header
  crates/handlers/src/compat/login.rs
  crates/handlers/src/compat/mod.rs
Labels: A-Compatibility-Layer, A-Spec-Compliance

#4405 Allow database tests to run in parallel again
  .config/nextest.toml
Labels: A-CI, T-Task

#4437 Fix starting up when no telemetry config is set
  crates/cli/src/main.rs
Labels: A-Configuration, T-Defect

#4435 Remove reference to unsupported aws_ses email transport
  docs/reference/configuration.md
Labels: A-Documentation

#4419 Fix headings in config doc
  docs/reference/configuration.md
Labels: A-Documentation

#4449 perf: avoid unnecessary parsing of user-agents
  crates/data-model/src/compat/session.rs
  crates/data-model/src/oauth2/device_code_grant.rs
  crates/data-model/src/oauth2/session.rs
  crates/data-model/src/user_agent.rs
  crates/data-model/src/users.rs
  crates/handlers/src/admin/model.rs
  crates/handlers/src/compat/login.rs
  crates/handlers/src/graphql/model/browser_sessions.rs
  crates/handlers/src/graphql/model/compat_sessions.rs
  crates/handlers/src/graphql/model/oauth.rs
  crates/handlers/src/oauth2/device/authorize.rs
  crates/handlers/src/oauth2/token.rs
  crates/handlers/src/upstream_oauth2/link.rs
  crates/handlers/src/views/login.rs
  crates/handlers/src/views/recovery/start.rs
  crates/handlers/src/views/register/password.rs
  crates/handlers/src/views/register/steps/finish.rs
  crates/storage-pg/src/app_session.rs
  crates/storage-pg/src/compat/mod.rs
  crates/storage-pg/src/compat/session.rs
  crates/storage-pg/src/oauth2/device_code_grant.rs
  crates/storage-pg/src/oauth2/mod.rs
  crates/storage-pg/src/oauth2/session.rs
  crates/storage-pg/src/user/recovery.rs
  crates/storage-pg/src/user/registration.rs
  crates/storage-pg/src/user/session.rs
  crates/storage/src/compat/session.rs
  crates/storage/src/oauth2/device_code_grant.rs
  crates/storage/src/oauth2/session.rs
  crates/storage/src/user/recovery.rs
  crates/storage/src/user/registration.rs
  crates/storage/src/user/session.rs
  crates/templates/src/context.rs
Labels: T-Task

#4451 perf: avoid unnecessary clones of the log context
  crates/cli/src/server.rs
  crates/context/src/fmt.rs
  crates/context/src/lib.rs
  crates/tasks/src/new_queue.rs
Labels: T-Task

#4452 Fix the ordering of the middlewares
  crates/cli/src/server.rs
Labels: T-Task

#4463 Avoid deadlocks when flushing session activities
  crates/handlers/src/activity_tracker/mod.rs
  crates/handlers/src/activity_tracker/worker.rs
  crates/storage-pg/src/compat/session.rs
  crates/storage-pg/src/oauth2/session.rs
  crates/storage-pg/src/user/session.rs
Labels: T-Defect

#4471 Allow user deactivation on the Synapse side to take longer than 30s
  crates/http/src/reqwest.rs
  crates/matrix-synapse/src/lib.rs
Labels: T-Task

#4447 Remove the old migration tool and document the new one
  .dockerignore
  .github/dependabot.yml
  .github/scripts/commit-and-tag.cjs
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/tag.yaml
  biome.json
  docker-bake.hcl
  docs/SUMMARY.md
  docs/reference/cli/config.md
  docs/reference/cli/syn2mas.md
  docs/setup/README.md
  docs/setup/migration.md
  docs/setup/well-known.md
  tools/syn2mas/.gitignore
  tools/syn2mas/.nvmrc
  tools/syn2mas/Dockerfile
  tools/syn2mas/LICENSE
  tools/syn2mas/README.md
  tools/syn2mas/package-lock.json
  tools/syn2mas/package.json
  tools/syn2mas/src/advisor.mts
  tools/syn2mas/src/db.mts
  tools/syn2mas/src/index.ts
  tools/syn2mas/src/migrate.mts
  tools/syn2mas/src/schemas/mas.mts
  tools/syn2mas/src/schemas/synapse.mts
  tools/syn2mas/src/types/MCompatAccessToken.d.ts
  tools/syn2mas/src/types/MCompatRefreshToken.d.ts
  tools/syn2mas/src/types/MCompatSession.d.ts
  tools/syn2mas/src/types/MUpstreamOauthLink.d.ts
  tools/syn2mas/src/types/MUpstreamOauthProvider.d.ts
  tools/syn2mas/src/types/MUser.d.ts
  tools/syn2mas/src/types/MUserEmail.d.ts
  tools/syn2mas/src/types/MUserPassword.d.ts
  tools/syn2mas/src/types/SAccessToken.d.ts
  tools/syn2mas/src/types/SRefreshToken.d.ts
  tools/syn2mas/src/types/SUser.d.ts
  tools/syn2mas/src/types/SUserExternalId.d.ts
  tools/syn2mas/src/types/SUserThreePid.d.ts
  tools/syn2mas/src/types/index.d.ts
  tools/syn2mas/src/types/knex.d.ts
  tools/syn2mas/tsconfig.eslint.json
  tools/syn2mas/tsconfig.json
Labels: A-Documentation

#4481 Bump all the frontend dependencies
  frontend/.storybook/public/mockServiceWorker.js
  frontend/package-lock.json
  frontend/package.json
Labels: A-Dependencies, T-Task, Z-Deps-Frontend
