Repository element-hq/matrix-authentication-service, pull requests merged in 2025-02, with the labels that each got.

#3961 Stop using cargo-chef in the docker build
  Dockerfile
Labels: A-CI, A-Container, T-Task

#3960 Use the x86-64-v2 pseudo-ABI when building for x86_64 targets
  .config/cargo.toml
Labels: T-Task

#3973 Refactor actions to reuse shared steps
  .github/actions/build-frontend/action.yml
  .github/actions/build-policies/action.yml
  .github/scripts/.gitignore
  .github/scripts/commit-and-tag.cjs
  .github/scripts/create-release-branch.cjs
  .github/scripts/create-version-tag.cjs
  .github/scripts/merge-back.cjs
  .github/scripts/package.json
  .github/scripts/update-release-branch.cjs
  .github/scripts/update-unstable-tag.cjs
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
  .github/workflows/merge-back.yaml
  .github/workflows/release-branch.yaml
  .github/workflows/release-bump.yaml
  .github/workflows/tag.yaml
  .github/workflows/translations-download.yaml
  .github/workflows/translations-upload.yaml
Labels: A-CI, T-Task

#3974 Update most Rust dependencies & disable some unused features
  Cargo.lock
  Cargo.toml
  crates/axum-utils/Cargo.toml
  crates/cli/Cargo.toml
  crates/data-model/Cargo.toml
  crates/handlers/Cargo.toml
  crates/http/Cargo.toml
  crates/http/src/reqwest.rs
Labels: A-Dependencies, Z-Deps-Backend

#3975 Fix the unstable build CI job
  .github/workflows/build.yaml
Labels: A-CI, T-Task

#3988 Document more `mas-cli` subcommands and standardise the format
  docs/SUMMARY.md
  docs/reference/cli/README.md
  docs/reference/cli/config.md
  docs/reference/cli/database.md
  docs/reference/cli/doctor.md
  docs/reference/cli/manage.md
  docs/reference/cli/server.md
  docs/reference/cli/templates.md
  docs/reference/cli/worker.md
Labels: A-Documentation

#3982 Update links to policy files
  docs/topics/policy.md
Labels: A-Documentation

#4001 Admin API to list and get user emails
  crates/handlers/src/admin/mod.rs
  crates/handlers/src/admin/model.rs
  crates/handlers/src/admin/v1/mod.rs
  crates/handlers/src/admin/v1/user_emails/get.rs
  crates/handlers/src/admin/v1/user_emails/list.rs
  crates/handlers/src/admin/v1/user_emails/mod.rs
  docs/api/spec.json
Labels: A-Admin-API, T-Enhancement

#4010 Fix the upstream OAuth 2.0 callback form deserialisation
  crates/handlers/src/upstream_oauth2/callback.rs
Labels: A-Upstream-OAuth, T-Defect

#4004 Admin API to list and get user sessions
  crates/handlers/src/admin/mod.rs
  crates/handlers/src/admin/model.rs
  crates/handlers/src/admin/v1/mod.rs
  crates/handlers/src/admin/v1/user_sessions/get.rs
  crates/handlers/src/admin/v1/user_sessions/list.rs
  crates/handlers/src/admin/v1/user_sessions/mod.rs
  docs/api/spec.json
Labels: A-Admin-API, T-Enhancement

#4011 Fix the user session admin API docs
  crates/handlers/src/admin/mod.rs
  docs/api/spec.json
Labels: A-Admin-API, A-Documentation

#4013 Enable operation deep-linking in the admin API docs
  docs/api/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/swagger.tsx
Labels: A-Admin-API, A-Documentation

#4012 Admin API to list and get upstream OAuth links
  crates/handlers/src/admin/mod.rs
  crates/handlers/src/admin/model.rs
  crates/handlers/src/admin/v1/mod.rs
  crates/handlers/src/admin/v1/upstream_oauth_links/get.rs
  crates/handlers/src/admin/v1/upstream_oauth_links/list.rs
  crates/handlers/src/admin/v1/upstream_oauth_links/mod.rs
  crates/storage-pg/src/upstream_oauth2/link.rs
  crates/storage-pg/src/upstream_oauth2/mod.rs
  crates/storage/src/upstream_oauth2/link.rs
  docs/api/spec.json
Labels: A-Admin-API, T-Enhancement

#4023 Fix the rendering of the embedded API doc
  frontend/knip.config.ts
  frontend/src/swagger.ts
  frontend/vite.config.ts
  templates/swagger/doc.html
Labels: A-Admin-API, A-Documentation

#3994 Simplify the setup documentation introduction
  docs/setup/README.md
Labels: A-Documentation

#4022 Experimental feature to automatically expire inactive sessions
  crates/cli/src/commands/server.rs
  crates/cli/src/commands/worker.rs
  crates/cli/src/util.rs
  crates/config/src/sections/experimental.rs
  crates/data-model/src/lib.rs
  crates/data-model/src/site_config.rs
  crates/handlers/src/admin/v1/oauth2_sessions/list.rs
  crates/handlers/src/test_utils.rs
  crates/storage-pg/src/iden.rs
  crates/storage-pg/src/oauth2/mod.rs
  crates/storage-pg/src/oauth2/session.rs
  crates/storage/src/oauth2/session.rs
  crates/storage/src/queue/tasks.rs
  crates/tasks/src/lib.rs
  crates/tasks/src/sessions.rs
  docs/api/spec.json
  docs/config.schema.json
  docs/reference/configuration.md
Labels: A-Device-Management, T-Enhancement

#4034 Fix the release workflow references to scripts
  .github/workflows/merge-back.yaml
  .github/workflows/release-branch.yaml
Labels: A-CI, T-Task

#4040 Fix the HTTP status code for the user creation admin endpoint
  crates/handlers/src/admin/v1/users/add.rs
  docs/api/spec.json
Labels: A-Admin-API, T-Defect

#4048 Allow banning IPs and user agents through the policy
  .github/actions/build-policies/action.yml
  crates/handlers/src/graphql/mod.rs
  crates/handlers/src/graphql/mutations/user.rs
  crates/handlers/src/graphql/mutations/user_email.rs
  crates/handlers/src/graphql/query/viewer.rs
  crates/handlers/src/graphql/state.rs
  crates/handlers/src/oauth2/authorization/complete.rs
  crates/handlers/src/oauth2/authorization/mod.rs
  crates/handlers/src/oauth2/consent.rs
  crates/handlers/src/oauth2/device/consent.rs
  crates/handlers/src/oauth2/registration.rs
  crates/handlers/src/oauth2/token.rs
  crates/handlers/src/upstream_oauth2/link.rs
  crates/handlers/src/views/register/password.rs
  crates/policy/src/bin/schema.rs
  crates/policy/src/lib.rs
  crates/policy/src/model.rs
  docs/reference/configuration.md
  policies/Makefile
  policies/authorization_grant/authorization_grant.rego
  policies/client_registration/client_registration.rego
  policies/common/common.rego
  policies/common/common_test.rego
  policies/email/email.rego
  policies/email/email_test.rego
  policies/register/register.rego
  policies/register/register_test.rego
  policies/schema/authorization_grant_input.json
  policies/schema/client_registration_input.json
  policies/schema/email_input.json
  policies/schema/password_input.json
  policies/schema/register_input.json
  templates/components/field.html
  translations/en.json
Labels: A-Policy, T-Enhancement

#4057 Fix upstream OAuth 2.0 callbacks using the form_post method
  crates/handlers/src/upstream_oauth2/callback.rs
Labels: A-Upstream-OAuth, T-Defect

#4058 Convert IPv6-mapped IPv4 addresses to IPv4 addresses
  crates/cli/src/app_state.rs
Labels: T-Enhancement

#4069 Fix a crash on startup when a listener has an empty prefix
  crates/cli/src/server.rs
Labels: T-Defect

#4075 Allow logging in using the deprecated 'user' property on the compat login API
  crates/handlers/src/compat/login.rs
  crates/handlers/src/test_utils.rs
Labels: A-Compatibility-Layer, T-Task, A-Spec-Compliance

#4091 Upgrade OpenTelemetry to 0.28
  Cargo.lock
  Cargo.toml
  crates/cli/src/main.rs
  crates/cli/src/telemetry.rs
  crates/config/src/sections/telemetry.rs
  docs/config.schema.json
Labels: A-Dependencies, Z-Deps-Backend

#4092 Upgrade ICU4X crates to 0.15
  Cargo.lock
  Cargo.toml
  crates/axum-utils/Cargo.toml
  crates/i18n/Cargo.toml
  crates/i18n/src/translator.rs
Labels: A-Dependencies, Z-Deps-Backend

#4106 Remove warnings about password auth not being feature complete
  tools/syn2mas/src/advisor.mts
Labels: A-Migration, T-Task

#4119 Trigger the build workflow on PRs with a label
  .github/scripts/cleanup-pr.cjs
  .github/workflows/build.yaml
Labels: A-CI, T-Task
