Repository element-hq/matrix-authentication-service, pull requests merged in 2025-07, with the labels that each got.

#4735 Miscellaneous housekeeping
  .gitignore
  clippy.toml
  crates/handlers/src/graphql/mod.rs
  crates/storage/src/compat/access_token.rs
  crates/storage/src/oauth2/client.rs
Labels: T-Task

#4744 Allow skipping GDPR-erasure when deactivating a user through the admin API
  crates/handlers/src/admin/v1/users/deactivate.rs
  docs/api/spec.json
Labels: A-Admin-API

#4808 Allow the homeserver to perform introspection using a shared secret
  crates/axum-utils/src/client_authorization.rs
  crates/handlers/src/oauth2/introspection.rs
  crates/matrix-synapse/src/legacy.rs
  crates/matrix-synapse/src/modern.rs
  crates/matrix/src/lib.rs
  crates/matrix/src/mock.rs
  crates/matrix/src/readonly.rs
Labels: A-Homeserver-Integration, T-Task

#4819 Fix spec compliance of upstream OAuth 2.0 client auth methods
  crates/oidc-client/src/types/client_credentials.rs
  crates/oidc-client/tests/it/types/client_credentials.rs
Labels: A-Upstream-OAuth, T-Defect, A-Spec-Compliance

#4843 Upgrade opentelemetry to 0.30.0
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend
