Repository element-hq/matrix-authentication-service, pull requests merged in 2025-01, with the labels that each got.

#3687 Additional fields in the GraphQL API for upstream providers
  crates/cli/src/commands/server.rs
  crates/handlers/src/graphql/mod.rs
  crates/handlers/src/graphql/model/upstream_oauth.rs
  crates/handlers/src/graphql/state.rs
  crates/handlers/src/test_utils.rs
  frontend/schema.graphql
  frontend/src/gql/graphql.ts
Labels: A-GraphQL

#3761 Upgrade to sqlx 0.8.3
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: A-Dependencies, Z-Deps-Backend

#3744 Remove unused dependencies and symbols using knip
  .github/workflows/ci.yaml
  frontend/i18next-parser.config.ts
  frontend/knip.config.ts
  frontend/locales/en.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/NotLoggedIn.tsx
  frontend/src/components/PasswordCreationDoubleInput.tsx
  frontend/src/components/SessionDetail/SessionDetails.tsx
  frontend/src/components/Typography.tsx
  frontend/src/components/UserProfile/UserEmailList.tsx
  frontend/src/config.ts
  frontend/src/pagination.ts
  frontend/src/result.ts
Labels: A-CI, A-Frontend, T-Task

#3752 Use taiki-e/install-action for installing some tools in CI
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
Labels: A-CI, T-Task

#3806 Bump Vitest to 6 and Vite to 3, and other dependecies updates
  frontend/package-lock.json
  frontend/package.json
Labels: A-Dependencies, Z-Deps-Frontend

#3847 Fix the unstable build
  .github/workflows/build.yaml
  .github/workflows/release.yaml
Labels: A-CI, T-Task

#3790 Add 'introspection_endpoint' to homeserver config example
  docs/setup/homeserver.md
Labels: A-Documentation, T-Task

#3908 Allow logging in with the full MXID
  Cargo.lock
  Cargo.toml
  crates/data-model/Cargo.toml
  crates/data-model/src/oauth2/authorization_grant.rs
  crates/handlers/src/compat/login.rs
  crates/handlers/src/views/login.rs
  crates/matrix/Cargo.toml
  crates/matrix/src/lib.rs
Labels: A-Compatibility-Layer, A-Login-Flow, T-Defect, A-Spec-Compliance

#3918 Don't prevent starting up if the mail backend is unavailable
  crates/cli/src/commands/server.rs
  crates/cli/src/commands/worker.rs
  crates/cli/src/util.rs
Labels: A-CLI, T-Task

#3920 Fix the account page crash introduced in #3893
  crates/handlers/src/oauth2/device/link.rs
  crates/handlers/src/views/app.rs
Labels: T-Defect

#3925 Fetch the upstream OIDC metadata in the background on startup
  crates/cli/src/app_state.rs
  crates/cli/src/commands/server.rs
Labels: T-Task
